### PR TITLE
Break into modules

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This PR breaks up the code into individual modules without changing the API (afaics).

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
I hope I find time to implement a high-level interface on top of this PR anytime soon.

**Comment by staktrace** [comment]
What is gained with this change? (It's gonna make blame harder, so unless we gain something worth more I'm not inclined to accept this)

**Comment by matthiasbeyer** [comment]
Wow, fast response!

Clarity and nothing more, tbh. I see why you wouldn't merge this and I agree on your points.

**Comment by staktrace** [comment]
> Wow, fast response!

You had good timing; I was checking my email in the morning and it happened to just line up with your PR hitting my inbox :)

> Clarity and nothing more, tbh. I see why you wouldn't merge this and I agree on your points.

Ok, I'll close this PR for now. If the situation changes and it makes sense to split this into modules I'm happy to reconsider.

**Pull request closed without merging**
