### PR TITLE
addrparse: parse quoted encoded words

### PR DESCRIPTION
**Pull request by link2xt**
This is probably a bug in the encoder, but accepting it is better than not parsing `From` at all.

### CODE REVIEW

**Comment by link2xt** [comment]
Related issue in Delta Chat repo: https://github.com/deltachat/deltachat-core-rust/issues/2192

**Comment by link2xt** [comment]
This fails with
```
thread 'addrparse::tests::parse_quoted_encoded' panicked at 'called `Result::unwrap()` on an `Err` value: Generic("Unexpected encoded word found inside a quoted name")', src/addrparse.rs:1074:39
```

**Comment by staktrace** [comment]
Looks reasonable, thanks!

**Comment by link2xt** [comment]
@staktrace Could you also push a release to crates.io?

**Comment by staktrace** [comment]
Already done! :)

**Comment by link2xt** [comment]
Thanks!

**Comment by r10s** [comment]
so fast! thanks for fixing!

**Comment by r10s** [comment]
meanwhile the original sender came back, the mail in question was generated by _MailMate by Freron_ - however, i can easily imagine it happens also for other clients :)

**Comment by staktrace** [comment]
Good to know, thanks!

**Pull request merged**
