### PR TITLE
Correctly parse mailboxes with commas in the name

### PR DESCRIPTION
**Pull request by link2xt**
This should help with https://github.com/deltachat/deltachat-core-rust/issues/1120

### CODE REVIEW

**Comment by staktrace** [comment]
@link2xt Hmm.. I think per the RFC something like `foo, bar <bar@baz.com>` would actually be invalid. The name part of this isn't allowed to have commas unless it's quoted. I'm a little reluctant to merge this without exploring other options. Where is the `foo, bar` coming from, and is there someplace upstream that can wrap it in quotes so that it parses properly?

**Comment by link2xt** [comment]
@staktrace Yes, seems like `phrase` can only `word`s without `,`. Let me update the test, it is a bit more complex actually.

**Comment by link2xt** [comment]
Test added, looking into how to quote this.

**Comment by link2xt** [comment]
@staktrace The problem is what to do if `decode_word` returns a string with a quote?

**Comment by link2xt** [comment]
The test right above the added one looks wrong by the way: why does it already contain commas?

**Comment by link2xt** [comment]
@staktrace What do you think about the testcase?

Maybe parse_header should not decode these strings at all, and `addrparse` will decode them instead?

**Comment by link2xt** [comment]
I have updated this PR with end-to-end test, but the solution is still a hack.

**Comment by staktrace** [comment]
Ah I see. This is a tricky problem. Let me think about it a bit.

**Comment by link2xt** [comment]
I think headers should be returned unparsed, as a new structure. If displayed, it should be unescaped. But when converted to `str`, it should be returned as-is, so user can parse it with addrparse. This is how `Value` in `serde_json` works: https://docs.serde.rs/serde_json/

Maybe apply this workaround now, cut a minor version and then make a major version with a breaking change and better API?

**Comment by staktrace** [comment]
> @staktrace The problem is what to do if `decode_word` returns a string with a quote?

I don't see why this is a problem. `decode_word` should be able to return quotes, as far as I can tell.

> The test right above the added one looks wrong by the way: why does the address already contain quotes?

That test was taken almost verbatim from an actual email I got, so the address name was quoted, and then encoded via quoted-printable. Per above, this should be fine.

> I think headers should be returned unparsed, as a new structure. If displayed, it should be unescaped. But when converted to str, it should be returned as-is, so user can parse it with addrparse. This is how Value in serde_json works: https://docs.serde.rs/serde_json/

I'm not sure I fully understand this. Specifically I don't think I understand what you mean by "unparsed", "unescaped" and "as-is" here. If you're suggesting that `MailHeader` should only expose the "raw" (i.e. encoded, line-broken) value, then I disagree.

Right now the solution I'm most leaning towards is to add something like

```rust
pub fn get_addrs(&self) -> Result<MailAddrList, MailParseError> {...};
```

to the `MailHeader` struct. This would effectively run `addrparse` on the header's `value`, and then do the quoted-printable decode afterwards, which presumably should give you the right result. The current code in `get_value` can be refactored a little bit so bits can be reused as necessary. Assuming this works out, would this API be satisfactory for you?

Fundamentally it seems like having `addrparse` separate from the quoted-printable decoding happening inside `MailHeader::get_value` means that things get done in the wrong order. The PR you have is basically a hack that works around this, but I'd like to avoid that kind of hack if possible. Also I think it's useful to have an `addrparse` function that operates like it does now, because people might want to use it in a more standalone way just to parse random address strings that come from other places and not from `MailHeader::get_value`. So I don't want to introduce changes there that would compromise that use case. And similarly, the way `MailHeader::get_value` works now is useful for a large number of use cases, where users just want to get a "useful" value out of it and not have to do any further processing on it. So I don't really want to modify that either. This is why I arrived at my currently-preferred solution of adding a `get_addrs` or similar function on `MailHeader` that combines the two but does the operations in the proper order.

**Comment by staktrace** [comment]
@link2xt After much refactoring I introduced a `addrparse_header` function which takes a `MailHeader` directly and produces the right thing for this scenario. Please give it a shot and let me know if you have any additional test cases that it's not handling properly. If not I can publish to crates.io.

**Comment by link2xt** [comment]
@staktrace I don't have any other testcases yet. The API works as expected, thanks!

If other problems are found, it should be possible to fix without changing the API and release a minor version.

**Pull request closed without merging**
